# Generated by Django 6.0.2 on 2026-02-14 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_segment_summary_segment_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workflow_id', models.CharField(editable=False, max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='catalogue.video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
