# Generated by Django 6.0.2 on 2026-02-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='segment',
            name='transcript',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
